공부 하다가 소소하게 알게된 것들을 모아놓은 곳.

########################################################################################
reference : https://stackoverflow.com/questions/49836676/error-after-upgrading-pip-cannot-import-name-main

간혹 pip 업데이트를 하고 나면 다음과 같은 오류가 뜰때가 있다
	Traceback (most recent call last):
	  File "/usr/bin/pip3", line 15, in <module>
	    sys.exit(__main__._main())
	AttributeError: module 'pip.__main__' has no attribute '_main'

pip update 이후(/usr/bin/pip 파일을 변경)
	import sys
	from pip import main
	if __name__ == '__main__':
	     sys.exit(main())
내용을
	import sys
	from pip import __main__
	if __name__ == '__main__':
	     sys.exit(__main__._main())
다음과 같이 변경하여서 해결하였다.
########################################################################################
